---
title: "mini-review"
author: "Yingjie"
date: "2023-03-29"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
# To clear your environment
remove(list = ls())

## Load common packages and directories
getwd()
# library(here)
# here()
# set_here()

## Additional packages
library(tidyverse)
library(splitstackshape) ## `cSplit()`
library(Hmisc)
today <- format(Sys.time(), "%Y%m%d"); today ## "%Y%m%d%H%M"

dir.raw <- "./data/"
dir.fig <- "./figures/"
```



# Data import
```{r include=FALSE}
getwd()

fs <- list.files(path = dir.raw, full.names = T, pattern = '.csv$'); fs
# csv <- "review_299449_20230330063918.csv"
csv <- fs[1]


dfs <- data.frame()

for (csv in fs) {
  
  # time <- basename(csv) %>% gsub('review_299449_', '', .) %>%
  #   str_sub(start = 1, end = 8)  %>%
  #   as.Date(., format = "%Y%m%d")
  # time
  
  t <- basename(csv) %>% gsub('review_299449_', '', .) %>%
    str_sub(start = 1, end = 14)  %>%
    as.POSIXct(.,format="%Y%m%d%H%M%S") 
  t
  
  d <- readr::read_csv(file = csv) %>%
    dplyr::mutate(date = t)
  
  dfs <- rbind(dfs, d)
  
}
```



```{r - pre-processing }
dt <- dfs %>%
  dplyr::rename('id' = 'Covidence #') %>%
  dplyr::rename(Reviewer = `Reviewer Name`) %>%
  dplyr::rename("Levels" = "Organizational levels of analysis",
                'Type' = 'Flow Type') 

dt_ <- dt %>%
  # arrange(desc(date)) %>%
  dplyr::distinct(id, .keep_all = T) %>%
  
  ## - remove text within parenthesis 
  dplyr::mutate(
    Levels = gsub("\\s*\\([^\\)]+\\)", "", Levels),
  ) %>%
  
  ## - remove unnecessary text 
  dplyr::mutate(
    Type = gsub("__ ", "", Type),
    Type = gsub("Other\\: ", "", Type),
    Levels = gsub("Other\\: ", "", Levels)) %>%
  as.data.frame()

# rm(d, dfs)

dt_ <- dt_ %>%
  dplyr::mutate(
     Levels = ifelse(id=='305' & Reviewer=='Xin Lan', 'International; National', Levels),
  )

names(dt_)
```


```{r - check errors}
dt_err <- dt_ %>%
  # dplyr::filter(str_detect(Type, fixed('other', ignore_case = T))) %>%
  # dplyr::filter(str_detect(Type, fixed('Carbon', ignore_case = T))) %>% 
  # dplyr::filter(str_detect(Type, fixed('Virtual wood', ignore_case = T))) %>% # ''
  # dplyr::filter(str_detect(Type, fixed('Ecosystem services', ignore_case = T))) %>% 
  # dplyr::filter(str_detect(Type, fixed('Policies', ignore_case = T))) %>% ## #267 by Nick
  dplyr::filter(str_detect(Type, fixed('Cultural practices', ignore_case = T))) %>% ## #93 by Nick
  # dplyr::filter(str_detect(Levels, fixed('ecoregion', ignore_case = T))) %>% 
  # dplyr::filter(is.na(`Data availability`)) %>% 
  ## Policies
  as.data.frame()

dt_err_ <- dt %>%
  # dplyr::filter(id == '320') %>%
  dplyr::filter(id == '358') %>%
  dplyr::distinct(id, .keep_all = T) %>%
  as.data.frame()
```



### - to-do list

* revise and then send for consensus
  - #358 by Nan - "virtual wood products"
  - #51, #682 - missing input for "Data availability"
  


## Proregss
```{r}
dt_ %>%
  group_by(Reviewer, date) %>%
  tally() %>%
  add_count(Reviewer, wt = n, name = 'n_total') %>%
  # dplyr::mutate(date = as.Date(date)) %>%
  ggplot(aes(x = reorder(Reviewer, n_total), y = n, fill = date)) +
  geom_col(show.legend = F) +
  geom_text(aes(label = n), 
            # vjust = 0.5, hjust = 0, 
            position = position_stack(vjust = 0.5),
            color = 'gray90') +
  
  geom_text(
    aes(label = after_stat(y), group = Reviewer), 
    stat = 'summary', fun = sum, vjust = .5, hjust = 0, color = 'red', fontface = 'bold', size = 5
  ) +

  xlab('') +
  coord_flip() +
  theme_bw()
```




# Data cleaning 

```{r - functions}
expand_col_to_long <- function(data, target_col = "Mental health Types") {
  data_long <- data %>%
    dplyr::rename("col_split" = target_col) %>%
    cSplit(
      indt = .,
      splitCols = c("col_split"),
      sep = ";|,",
      drop = F, # drop the original col or not
      direction = "long", # this is better than "wide"
      stripWhite = T
    ) %>% # clean white space
    dplyr::mutate(across(where(is.factor), as.character)) %>%
    dplyr::mutate(col_split = trimws(col_split)) %>%

    ## capitalizes first word but not subsequent words
    dplyr::mutate(col_split = Hmisc::capitalize(col_split)) %>%
    as.data.frame() %>%
    # group_by(col_split) %>%
    # dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
    as.data.frame()

  ## change back to the original column name
  names(data_long)[names(data_long) == "col_split"] <- target_col

  return(data_long)
}



plot_freq <- function(data, var = "Mental health Types") {
  p <- ggplot(
    data = data,
    aes(
      x = reorder(eval(parse(text = var)), n),
      y = n,
      # fill = n
  )) +
  geom_col() +
  theme_bw() +
  # theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  coord_flip() +
  # scale_fill_distiller(name = '', palette = "Blues", guide = "colorbar", direction = 1) +
  xlab("")
  
  return(p)
}
```


```{r - Type, include=FALSE}
## keep columns of interest, and clean data

type_top_colors <- c('#1f78b4','#a6cee3','#b2df8a')
type_top_levels <- c('Physical Flows', 'Non-material Flows', 'Virtual Flows')
org_levels <- c("International", "National", "Subnational", "Local")


## stat
## - by Type
dt.bymhi <- dt_ %>%
  group_by(Type, Levels) %>%
  dplyr::count() %>%
  ungroup() %>%
  as.data.frame()

physical_flow_list <- c(
  'raw materials', 'goods and products', 'energy', 'water', 'pollutants/waste', 'animal migration',
  'species dispersal', 'disease transmission', 'people',
  'sediment'
) %>%
  Hmisc::capitalize(.)
  

## - clean and format
dt.bymhi.cl <- dt.bymhi %>%
  dplyr::mutate(
    Type = gsub("\\(e\\.g\\., land grab, land acquisition, land requisition\\)", "", Type),
    
    ) %>%
  expand_col_to_long(data = ., target_col = "Type") %>%
  dplyr::filter(Type != 'Physical Flows') %>%
  ## clear text and add top category 
  dplyr::mutate(
    
    Type = trimws(Type),
    
    ## fix manual input values
    Type = ifelse(Type %in% c('Animals (trade)', 'Animals (pandas)', 'Animals (illegal trade)',
                              'Wildlife trade'), 
                  'goods and products', Type),
    
    Type = ifelse(Type %in% c('Land requisition'), 'transfer ownership and use of land', Type),
    Type = ifelse(Type %in% c('Virtual nitrogen', 'Virtual phosphorus'), 'Virtual N/P', Type),
    Type = ifelse(Type %in% c('Carbon'), 'Pollutants/waste', Type),
    Type = Hmisc::capitalize(Type),
    
    type_top = case_when(
      str_detect(Type, regex('virtual|footprint', ignore_case=TRUE)) ~ 'Virtual Flows',
      Type %in% physical_flow_list ~ 'Physical Flows',
      TRUE ~ 'Non-material Flows'),
    type_top = factor(type_top, levels = type_top_levels),
    
    
    ## rename flows
    Type = ifelse(Type %in% c('Cultural ecosystem services'), 'Cultural ES', Type),
    Type = ifelse(Type %in% c('Goods and products', 'Energy'), 'Goods', Type),
    Type = ifelse(Type %in% c('Financial/investments'), 'Financial', Type),
    Type = ifelse(Type %in% c('People'), 'Human', Type),
    Type = ifelse(Type %in% c('Sediment'), 'Water', Type),
    Type = ifelse(Type %in% c('Transfer ownership and use of land'), 'Land deals', Type),
    Type = ifelse(Type %in% c('Technology', 'Knowledge', 'Land deals'), 'Information', Type),
    Type = ifelse(Type %in% c('Virtual GHG emissions'), 'Virtual emissions', Type), 
    Type = ifelse(Type %in% c('Social footprints/risks'), 'Social footprints', Type),
    Type = ifelse(Type %in% c('Carbon', 'Pollutants/waste'), 'Pollutants', Type),
    
  ) %>%
  dplyr::filter(!Type %in% c(
    'Other', 'Virtual wood products trade', 
    'Policies',
    'Cultural practices',
    'Ecosystem services' ## overlapped with other input
    )) %>%
  as.data.frame()
  
  
dt.bymhi.clean <- dt.bymhi.cl  %>%
  group_by(Type, type_top) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  arrange(type_top) %>%
  as.data.frame()
```





```{r - Levels, include=FALSE}
## - by scale
dt.bylevel <- dt_ %>%
  ### -clean up the names of the tools
  # dplyr::select(1:5, Levels, -Title) %>%
  # dplyr::filter(nchar(Levels) < 180) %>%
  # dplyr::filter(str_detect(string = Levels, pattern = "exclude", negate = T)) %>%
  # dplyr::mutate(
  #   Tool = gsub("scales|Scales", "scale", Levels),
  #   Tool = gsub("\\s*\\([^\\)]+\\)", "", Tool)) %>% ## remove any strings in a ()
  
  ### - stat
  group_by(Levels, `Data availability`) %>%
  dplyr::count() %>%
  ungroup() %>%
  dplyr::filter(Levels != 'NA') %>%
  as.data.frame()



func_clean_levels <- function(data, target_col = "Levels") {
  
  dd <- expand_col_to_long(data = data, target_col = "Levels") %>%
  
  ## clear text and add top category ----------------
  dplyr::mutate(
    Levels = gsub('and|And|\\.|\\-', '', Levels),
    Levels = trimws(Levels),
    Levels = Hmisc::capitalize(Levels),
  ) %>%
  dplyr::filter(!Levels %in% c(
    'Biome', 'Ecoregion', 'River basin', 'Other:'
    )) %>%
  as.data.frame()
  
  return(dd)
  
}

dt.bylevel.cl <- func_clean_levels(data = dt.bylevel) %>%
  group_by(Levels, `Data availability`) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  as.data.frame()
  
  
dt.bylevel.clean <- dt.bylevel.cl  %>%
  dplyr::mutate(
    Levels = factor(Levels, levels = org_levels)
    ) %>%
  as.data.frame()

# dt.bylevel.clean$Levels <- factor(x = dt.bylevel.clean$Levels, levels = org_levels)
levels(dt.bylevel.clean$Levels)
```





```{r - Type + Levels}
dt.bymhi.cl2 <- dt.bymhi.cl  %>%
  # expand_col_to_long(data = ., target_col = "Levels") %>%
  func_clean_levels(data = .) %>%
  group_by(type_top, Type, Levels) %>%
  dplyr::summarise_at(c("n"), sum, na.rm = T) %>%
  # arrange(type_top) %>%
  dplyr::mutate(id = row_number()) %>%
  pivot_longer(names_to = 'dimension', 
               values_to = 'layers', 
               cols = c('type_top', 'Type', 'Levels')) %>%
  group_by(dimension) %>%
  dplyr::mutate(id_within_layers = row_number(dimension)) %>%
  arrange(dimension) %>%
  dplyr::rename(freq = n) %>%
  dplyr::mutate(
    dimension = factor(dimension, levels = c('Type', 'type_top', 'Levels')),
    # layers = factor(layers, levels = org_levels)
    ) %>%
  as.data.frame()
  


str(dt.bymhi.cl2)

dt.bymhi.clean_sort <- dt.bymhi.clean %>%
  group_by(type_top) %>%
  arrange(type_top, n)
str(dt.bymhi.clean)
dt.bymhi.clean_sort$Type

sort_by <- c(dt.bymhi.clean_sort$Type, levels(dt.bymhi.clean_sort$type_top), org_levels)
  
dt.bymhi.cl3 <- dt.bymhi.cl2 %>%
  dplyr::mutate(
    layers = factor(layers, levels = sort_by),
    )


library(RColorBrewer)
colourCount = length(unique(dt.bymhi.cl2$layers))
getPalette = colorRampPalette(brewer.pal(12, "Paired"))
 


library(ggalluvial)
width_my <- 1/2.5


dt.bymhi.cl2 %>%
  ggplot(.,
       aes(x = dimension, 
           y = freq,
           alluvium = id_within_layers, 
           stratum = layers, 
           fill = layers, 
           label = layers)) +
  scale_x_discrete(expand = c(.1, 0)) +
  # scale_fill_manual(values = getPalette(colourCount)) +
  # geom_flow(width = width_my) +
  geom_flow(width = width_my,
            # aes.bind = TRUE,
            decreasing = TRUE) +
  geom_stratum(alpha = .6, width = width_my, 
               decreasing = TRUE) +
  stat_stratum(geom = "text", 
               decreasing = TRUE) +
  # geom_text(stat = "stratum", check_overlap = T,
  #           # aes(label = paste0(stratum,
  #           #                    ifelse(nchar(as.character(stratum)) == 1L,
  #           #                           ": ", "\n"),
  #           #                    after_stat(n)))
  #           ) +
  theme_classic() +
  theme(legend.position = "none",
        axis.title  = element_blank(),
        axis.line = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(size=rel(1.4), 
                                   vjust = 10,
                                   margin = margin(t = 0, r = 0, b = 0, l = 0)))

getwd()
f <- 'FlowType_scale_pairs1.png'
fname <- paste0(dir.fig, f); fname
ggsave(filename = fname, plot = last_plot(), width = 16/1.5, height = 10, units = 'in', dpi = 300)

```

```{r - test 1, eval=FALSE, include=FALSE}
aes.bind_my <- "flows"
# aes.bind_my <- "alluvia"

dt.bymhi.cl2 %>%
  ggplot(.,
       aes(x = dimension, 
           y = freq,
           alluvium = id_within_layers, 
           stratum = layers, 
           fill = layers, 
           label = layers)) +
  scale_x_discrete(expand = c(.1, 0)) +
  geom_flow(width = width_my) +
  
  # geom_flow(width = width_my,
  #           decreasing = TRUE) +
  
  stat_alluvium(aes.bind = aes.bind_my) +
  # geom_stratum(alpha = .5, width = width_my, 
  #              decreasing = TRUE) +
  stat_stratum() +
  stat_stratum(geom = "text") +
  stat_alluvium(geom = "text", 
                aes.bind = aes.bind_my) +
  theme_classic() +
  theme(legend.position = "none",
        axis.title  = element_blank(),
        axis.line = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(size=rel(1.4), 
                                   vjust = 10,
                                   margin = margin(t = 0, r = 0, b = 0, l = 0)))

f <- paste0('FlowType_scale_pairs_', aes.bind_my, '.png')
fname <- paste0(dir.fig, f); fname
ggsave(filename = fname, plot = last_plot(), width = 16/1.5, height = 10, units = 'in', dpi = 300)
```



```{r - test 2, eval=FALSE, include=FALSE}
dt.bymhi.cl3 %>%
  ggplot(.,
       aes(x = dimension, 
           y = freq,
           alluvium = id_within_layers, 
           stratum = layers, 
           fill = layers, 
           label = layers)) +
  scale_x_discrete(expand = c(.1, 0)) +
  geom_flow(width = width_my) +
  geom_stratum(alpha = .5, width = width_my) +
  stat_stratum(geom = "text") +
  theme_classic() +
  theme(legend.position = "none",
        axis.title  = element_blank(),
        axis.line = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(size=rel(1.4), 
                                   vjust = 10,
                                   margin = margin(t = 0, r = 0, b = 0, l = 0)))


getwd()
f <- 'FlowType_scale_pairs0.png'
fname <- paste0(dir.fig, f); fname
ggsave(filename = fname, plot = last_plot(), width = 16/1.5, height = 10, units = 'in', dpi = 300)
```






# Viz

## Count by Type

```{r}
dt.bymhi.clean %>%
  dplyr::slice_max(order_by = n, n = 20) %>%
  ggplot(aes(
    x = reorder(Type, n),
    y = n,
    fill = type_top
  )) +
  geom_col() +
  
  coord_flip() +
  # scale_fill_distiller(name = '', palette = "Blues", guide = "colorbar", direction = 1) +
  scale_fill_manual(values = type_top_colors, name = 'Categories') +
  xlab("") +
  ggtitle("Frequency of Flow Types") +
  theme_bw() +
  theme(
    # axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), 
    legend.position = c(0.8, 0.15)
    )

fname <- paste0(dir.fig, "flow_types.png")
# ggsave(filename = fname, plot = last_plot(), width = 16 / 3, height = 9 / 3, units = "in", dpi = 300, bg = NULL)
```


## Count by tool

```{r}
dt.bylevel.clean %>%
  # dplyr::slice_max(order_by = n, n = 20) %>%
  # plot_freq(data = ., var = 'Levels') +
  ggplot(aes(
    x = Levels,
    y = n,
    # fill = type_top
  )) +
  geom_col() +
  # scale_x_reverse() +
  scale_x_discrete(limits=rev) +
  
  coord_flip() +
  xlab("") +
  theme_bw() +
  ggtitle("Frequency of Organizational levels")

fname <- paste0(dir.fig, "org_levels.png")
# ggsave(filename = fname, plot = last_plot(), width = 16 / 2, height = 9 / 2, units = "in", dpi = 300, bg = NULL)
```


